### ISSUE TITLE
Make site responsive for max-width: 720px

### ISSUE THREAD

**Issue by geeky-developer** [geeky-developer/shopping-cart#1]
Don't hesitate to leave a star⭐

**Comment by OgaDavid** [comment]
![2022-10-14-15-31-39](https://user-images.githubusercontent.com/104001201/195872110-67e22136-97e7-4a7c-9800-a641d4506be1.png)


I'd love to work on this but this is what i'm seeing on the site.

**Comment by geeky-developer** [comment]
There was some issue in linking the css file and handling the images .i have fixed the css linking rest about image then i have to replace it  from images folder of this repo .
If u can modify this change then i can create another issue regarding this and you can further continue upon this one else i will do it myslef by tommorow.

**Comment by AshishSharma1203** [comment]
Is this still unassigned ??? If yes, then i want to work upon this ??

**Comment by ghost** [comment]
Kindly assign me this task i'll do it
