### ISSUE TITLE
Make a PR template 

### ISSUE THREAD

**Issue by geeky-developer** [geeky-developer/shopping-cart#6]
make a PR template file in .github folder

**Comment by SabujGolui** [comment]
assign it to me, ill love to work

**Comment by AshishSharma1203** [comment]
Can I work upon this ??

**Comment by AnupeshVerma** [comment]
please assign this task to me, i have already solved an issue of adding newsletter in this repo

**Comment by AnupeshVerma** [comment]
!assign
